<?php
declare(strict_types=1);
require __DIR__ . '/../app/bootstrap.php';

use App\Core\Auth; use App\Core\DB; use App\Core\Security; use App\Support\View; use App\Support\Jalali; use App\Services\Audit; use App\Services\FollowUpService; use App\Services\SalaryService; use App\Services\RetentionService; use App\Services\BackupService;

Security::verifyCsrf();
$modules = require base_path('config/modules.php');
$route = $_GET['r'] ?? 'dashboard';

function toast(string $msg): void { $_SESSION['toast']=$msg; }
function money($n): string { return Jalali::fa(number_format((float)$n)) . ' ریال'; }
function status_badge(?string $s): string { $map=['active'=>'success','vip'=>'warning','new'=>'info','inactive'=>'secondary','at_risk'=>'danger','lost'=>'dark','pending'=>'warning','confirmed'=>'info','completed'=>'success','cancelled'=>'danger','no_show'=>'dark','paid'=>'success','partial'=>'warning','unpaid'=>'danger']; return '<span class="badge text-bg-'.($map[$s]??'secondary').'">'.e(t($s ?? '', $s ?? '')).'</span>'; }
function module_perm(string $module, string $action='view'): string { return $module . '.' . ($action==='manage'?'manage':$action); }
function can_module(string $module, string $action='view'): void { global $modules; Auth::requireCan(($modules[$module]['perm'] ?? $module).'.'.($action==='view'?'view':'manage')); }

function field_value(string $type, mixed $value): string { if(str_contains($type,'date') && $value) return Jalali::toJalali((string)$value); return (string)($value ?? ''); }
function normalize_post(array $fields): array { $data=[]; foreach($fields as $name=>$f){ if(!array_key_exists($name,$_POST)) continue; $type=$f[1]; $val=$_POST[$name]; if($type==='date') $val=Jalali::toGregorian((string)$val); elseif($type==='number') $val=(Jalali::en((string)$val)==='' ? 0 : Jalali::en((string)$val)); elseif($type==='services_multi') $val=json_encode($val ?: [], JSON_UNESCAPED_UNICODE); elseif(is_string($val)) $val=Security::cleanString(Jalali::en($val)); $data[$name]=$val; } return $data; }
function validate_required(array $fields, array $data): array { $err=[]; foreach($fields as $n=>$f){ if(in_array('required',$f,true) && (($data[$n]??'')==='' || ($data[$n]??null)===null)) $err[]=$f[0].' الزامی است.'; } return $err; }

function options(string $type): array { return match($type){
 'customer'=>DB::select("SELECT id, CONCAT(first_name,' ',last_name,' - ',mobile) label FROM customers WHERE deleted_at IS NULL ORDER BY id DESC LIMIT 500"),
 'therapist'=>DB::select("SELECT id, CONCAT(name,' (',code,')') label FROM therapists WHERE status='active' ORDER BY name"),
 'service'=>DB::select("SELECT id, name label FROM services WHERE status='active' ORDER BY name"),
 'appointment'=>DB::select("SELECT id, CONCAT(appointment_date,' ',start_time,' #',id) label FROM appointments ORDER BY appointment_date DESC LIMIT 500"),
 default=>[]}; }
function input_html(string $name, array $f, mixed $value=null): string { $label=$f[0]; $type=$f[1]; $req=in_array('required',$f,true)?'required':''; $val=e(field_value($type,$value)); $html='<label class="form-label">'.e($label).'</label>'; if($type==='textarea') return $html."<textarea name='$name' class='form-control' rows='3' $req>$val</textarea>"; if($type==='select'){ $html.="<select name='$name' class='form-select' $req>"; foreach($f[2] as $k=>$v){$sel=(string)$value===(string)$k?'selected':''; $html.="<option value='".e($k)."' $sel>".e($v)."</option>";} return $html.'</select>'; } if(in_array($type,['customer','therapist','service','appointment'],true)){ $html.="<select name='$name' class='form-select searchable' $req><option value=''>انتخاب کنید</option>"; foreach(options($type) as $o){$sel=(string)$value===(string)$o['id']?'selected':''; $html.="<option value='".e($o['id'])."' $sel>".e($o['label'])."</option>";} return $html.'</select>'; } if($type==='services_multi'){ $selected=json_decode((string)($value ?: '[]'), true) ?: []; $html.="<select name='{$name}[]' class='form-select' multiple>"; foreach(options('service') as $o){$sel=in_array((string)$o['id'], array_map('strval',$selected), true)?'selected':''; $html.="<option value='".e($o['id'])."' $sel>".e($o['label'])."</option>";} return $html.'</select><div class="form-text">برای انتخاب چند مورد کلید Ctrl را نگه دارید.</div>'; } return $html."<input type='$type' name='$name' value='$val' class='form-control' $req>"; }

function list_sql(string $module, array $def, string $where, array $params): array { $table=$def['table']; $select="$table.*"; $join=''; if(in_array($module,['appointments','sessions'],true)){ $select.=" , CONCAT(c.first_name,' ',c.last_name) customer_name, t.name therapist_name, s.name service_name"; $join=" LEFT JOIN customers c ON c.id=$table.customer_id LEFT JOIN therapists t ON t.id=$table.therapist_id LEFT JOIN services s ON s.id=$table.service_id"; } if($module==='packages'){ $select.=" , CONCAT(c.first_name,' ',c.last_name) customer_name"; $join=" LEFT JOIN customers c ON c.id=$table.customer_id"; } if($module==='customers'){ $select.=" , CONCAT(first_name,' ',last_name) full_name, (SELECT MAX(massage_date) FROM massage_sessions ms WHERE ms.customer_id=customers.id AND status='completed') last_visit, (SELECT COALESCE(SUM(final_amount),0) FROM massage_sessions ms WHERE ms.customer_id=customers.id AND status='completed') total_spent"; }
 $sql="SELECT $select FROM $table $join WHERE $where ORDER BY $table.id DESC"; return [$sql,$params]; }
function render_module_list(string $module): string { global $modules; $def=$modules[$module]; can_module($module); $table=$def['table']; $q=Security::cleanString($_GET['q'] ?? null); $page=max(1,(int)($_GET['page']??1)); $per=20; $where="$table.deleted_at IS NULL"; $params=[]; if($q){$ors=[]; foreach($def['search'] as $c){$ors[]="$table.$c LIKE ?"; $params[]="%$q%";} $where.=' AND ('.implode(' OR ',$ors).')';}
 [$sql,$params]=list_sql($module,$def,$where,$params); $total=(int)DB::value("SELECT COUNT(*) FROM $table WHERE $where", $params); $rows=DB::select($sql." LIMIT $per OFFSET ".(($page-1)*$per), $params); ob_start(); ?>
<div class="card p-3"><div class="d-flex flex-wrap gap-2 justify-content-between mb-3"><form class="d-flex gap-2"><input type="hidden" name="r" value="<?=e($module)?>"><input name="q" value="<?=e($q)?>" class="form-control" placeholder="جستجو..."><button class="btn btn-soft">جستجو</button></form><?php if(Auth::can($def['perm'].'.manage')): ?><a class="btn btn-primary" href="<?=url($module.'.create')?>"><i class="bi bi-plus-lg"></i> افزودن</a><?php endif;?></div><div class="table-responsive"><table class="table align-middle"><thead><tr><?php foreach($def['columns'] as $c=>$l): ?><th><?=e($l)?></th><?php endforeach;?><th>عملیات</th></tr></thead><tbody><?php foreach($rows as $row): ?><tr><?php foreach($def['columns'] as $c=>$l): ?><td><?php $v=$row[$c]??''; echo str_contains($c,'date')||str_contains($c,'visit')||str_ends_with($c,'_at')?e(Jalali::toJalali($v)): (str_contains($c,'amount')||str_contains($c,'price')||str_contains($c,'spent')?money($v):(str_contains($c,'status')||$c==='segment'?status_badge($v):e($v))); ?></td><?php endforeach; ?><td class="text-nowrap"><a class="btn btn-sm btn-soft" href="<?=url($module.'.show',['id'=>$row['id']])?>">نمایش</a><?php if(Auth::can($def['perm'].'.manage')): ?> <a class="btn btn-sm btn-outline-primary" href="<?=url($module.'.edit',['id'=>$row['id']])?>">ویرایش</a> <form method="post" action="<?=url($module.'.delete',['id'=>$row['id']])?>" class="d-inline" onsubmit="return confirm('حذف شود؟')"><?=View::csrf()?><button class="btn btn-sm btn-outline-danger">حذف</button></form><?php endif;?></td></tr><?php endforeach; if(!$rows): ?><tr><td colspan="20" class="empty">رکوردی یافت نشد.</td></tr><?php endif;?></tbody></table></div><div class="small text-muted">تعداد: <?=Jalali::fa($total)?></div></div><?php return (string)ob_get_clean(); }
function module_form(string $module, ?int $id=null, array $errors=[]): string { global $modules; $def=$modules[$module]; $row=$id?DB::row('SELECT * FROM '.$def['table'].' WHERE id=?',[$id]):[]; ob_start(); if($errors) echo '<div class="alert alert-danger">'.implode('<br>',array_map('e',$errors)).'</div>'; ?><form method="post" class="card p-4"><?=View::csrf()?><div class="row g-3"><?php foreach($def['fields'] as $n=>$f): ?><div class="col-md-6 <?=($f[1]==='textarea'||$f[1]==='services_multi')?'col-lg-12':''?>"><?=input_html($n,$f,$row[$n] ?? null)?></div><?php endforeach;?></div><div class="mt-4 d-flex gap-2"><button class="btn btn-primary">ذخیره</button><a class="btn btn-soft" href="<?=url($module)?>">انصراف</a></div></form><?php return (string)ob_get_clean(); }
function handle_module(string $module, string $action): void { global $modules; $def=$modules[$module]; $table=$def['table']; if($action==='index') echo View::render($def['title'], render_module_list($module)); elseif($action==='create'){ can_module($module,'manage'); if($_SERVER['REQUEST_METHOD']==='POST'){ $data=normalize_post($def['fields']); $errors=validate_required($def['fields'],$data); if($module==='appointments') $errors=array_merge($errors, check_double_booking($data)); if(!$errors){ if($module==='customers') {$data['customer_code']='C'.date('ymd').random_int(100,999); $data['registration_date']=date('Y-m-d');} $data['created_by']=Auth::id(); $data['created_at']=date('Y-m-d H:i:s'); $id=DB::insert($table,$data); after_save($module,$id,$data,true); Audit::log($module.'.create',$table,$id); toast('رکورد با موفقیت ایجاد شد.'); redirect($module.'.show',['id'=>$id]); } echo View::render('افزودن '.$def['title'], module_form($module,null,$errors)); } else echo View::render('افزودن '.$def['title'], module_form($module)); } elseif($action==='edit'){ can_module($module,'manage'); $id=(int)$_GET['id']; if($_SERVER['REQUEST_METHOD']==='POST'){ $data=normalize_post($def['fields']); $errors=validate_required($def['fields'],$data); if($module==='appointments') $errors=array_merge($errors, check_double_booking($data,$id)); if(!$errors){ $data['updated_at']=date('Y-m-d H:i:s'); DB::update($table,$data,'id=:id',['id'=>$id]); after_save($module,$id,$data,false); Audit::log($module.'.update',$table,$id); toast('رکورد بروزرسانی شد.'); redirect($module.'.show',['id'=>$id]); } echo View::render('ویرایش '.$def['title'], module_form($module,$id,$errors)); } else echo View::render('ویرایش '.$def['title'], module_form($module,$id)); } elseif($action==='delete'){ can_module($module,'manage'); DB::exec("UPDATE $table SET deleted_at=NOW() WHERE id=?",[(int)$_GET['id']]); Audit::log($module.'.delete',$table,(int)$_GET['id']); toast('رکورد حذف شد.'); redirect($module); } elseif($action==='show'){ echo View::render($def['title'], show_record($module,(int)$_GET['id'])); } }
function check_double_booking(array $data, int $ignoreId=0): array { if(empty($data['therapist_id'])||empty($data['appointment_date'])||empty($data['start_time'])||empty($data['end_time'])) return []; $row=DB::row("SELECT id FROM appointments WHERE therapist_id=? AND appointment_date=? AND status NOT IN ('cancelled','no_show') AND id<>? AND (start_time < ? AND end_time > ?) LIMIT 1",[$data['therapist_id'],$data['appointment_date'],$ignoreId,$data['end_time'],$data['start_time']]); return $row?['این درمانگر در بازه زمانی انتخاب‌شده نوبت دیگری دارد.']:[]; }
function after_save(string $module, int $id, array $data, bool $new): void { if($module==='sessions' && (($data['status']??'completed')==='completed')){ FollowUpService::createForSession($id); DB::insert('customer_timeline',['customer_id'=>$data['customer_id'],'type'=>'session','title'=>'ثبت جلسه ماساژ','body'=>'مبلغ: '.($data['final_amount']??0),'entity'=>'massage_sessions','entity_id'=>$id,'created_at'=>date('Y-m-d H:i:s')]); } if($module==='customers' && $new) DB::insert('customer_timeline',['customer_id'=>$id,'type'=>'registration','title'=>'ثبت‌نام مشتری','body'=>'پرونده مشتری ایجاد شد','created_at'=>date('Y-m-d H:i:s')]); }
function show_record(string $module, int $id): string { global $modules; $def=$modules[$module]; $row=DB::row('SELECT * FROM '.$def['table'].' WHERE id=?',[$id]); if(!$row) return '<div class="alert alert-warning">یافت نشد.</div>'; ob_start(); ?><div class="card p-4"><div class="d-flex justify-content-between"><h3><?=e($def['title'])?> #<?=Jalali::fa($id)?></h3><a class="btn btn-outline-primary" href="<?=url($module.'.edit',['id'=>$id])?>">ویرایش</a></div><div class="row g-3 mt-2"><?php foreach($def['fields'] as $n=>$f): ?><div class="col-md-6"><div class="meta"><span><?=e($f[0])?></span><b><?=e(field_value($f[1],$row[$n]??''))?></b></div></div><?php endforeach;?></div></div><?php if($module==='customers') echo customer_profile_extra($id); return (string)ob_get_clean(); }
function customer_profile_extra(int $id): string { $metrics=DB::row("SELECT COUNT(*) visits, MIN(massage_date) first_visit, MAX(massage_date) last_visit, COALESCE(SUM(final_amount),0) total, AVG(final_amount) avg_spend, AVG(satisfaction_score) avg_score FROM massage_sessions WHERE customer_id=? AND status='completed'",[$id]); $tl=DB::select('SELECT * FROM customer_timeline WHERE customer_id=? ORDER BY created_at DESC LIMIT 50',[$id]); ob_start(); ?><div class="row g-3 mt-1"><div class="col-md-3"><div class="stat"><span>تعداد مراجعات</span><b><?=Jalali::fa($metrics['visits']??0)?></b></div></div><div class="col-md-3"><div class="stat"><span>آخرین مراجعه</span><b><?=Jalali::toJalali($metrics['last_visit']??'')?></b></div></div><div class="col-md-3"><div class="stat"><span>کل خرید</span><b><?=money($metrics['total']??0)?></b></div></div><div class="col-md-3"><div class="stat"><span>رضایت میانگین</span><b><?=Jalali::fa(round((float)($metrics['avg_score']??0),1))?></b></div></div></div><div class="card p-4 mt-3"><h4>تایم‌لاین CRM</h4><div class="timeline"><?php foreach($tl as $i): ?><div><time><?=Jalali::toJalali($i['created_at'])?></time><b><?=e($i['title'])?></b><p><?=e($i['body'])?></p></div><?php endforeach; if(!$tl): ?><p class="empty">هنوز رویدادی ثبت نشده است.</p><?php endif;?></div></div><?php return (string)ob_get_clean(); }

if($route==='login'){ if(Auth::user()) redirect('dashboard'); if($_SERVER['REQUEST_METHOD']==='POST'){ if(!Security::rateLimit('login',5,300)) $error='تلاش بیش از حد. چند دقیقه بعد امتحان کنید.'; elseif(Auth::login($_POST['email']??'', $_POST['password']??'')) redirect('dashboard'); else $error='ایمیل یا رمز عبور اشتباه است.'; } ob_start(); ?><div class="auth-card"><h1>ورود به سامانه مدیریت ماساژ</h1><?php if(!empty($error)): ?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?><form method="post"><?=View::csrf()?><label class="form-label">ایمیل</label><input name="email" type="email" class="form-control" required value="admin@example.com"><label class="form-label mt-3">رمز عبور</label><input name="password" type="password" class="form-control" required value="password"><button class="btn btn-primary w-100 mt-4">ورود امن</button></form><p class="text-muted small mt-3">حساب پیش‌فرض: admin@example.com / password</p></div><?php echo View::render('ورود', ob_get_clean()); exit; }
if($route==='logout'){ Auth::logout(); redirect('login'); }
Auth::requireLogin();

if(isset($modules[$route])) { handle_module($route,'index'); exit; }
if(preg_match('/^([a-z_]+)\.(create|edit|delete|show)$/',$route,$m) && isset($modules[$m[1]])){ handle_module($m[1],$m[2]); exit; }

if($route==='dashboard'){ Auth::requireCan('dashboard.view'); $today=date('Y-m-d'); $stats=['appt'=>DB::value('SELECT COUNT(*) FROM appointments WHERE appointment_date=?',[$today]),'sessions'=>DB::value("SELECT COUNT(*) FROM massage_sessions WHERE massage_date=? AND status='completed'",[$today]),'revenue'=>DB::value("SELECT COALESCE(SUM(final_amount),0) FROM massage_sessions WHERE massage_date=? AND status='completed'",[$today]),'month'=>DB::value("SELECT COALESCE(SUM(final_amount),0) FROM massage_sessions WHERE massage_date>=DATE_FORMAT(CURDATE(),'%Y-%m-01') AND status='completed'"),'new'=>DB::value('SELECT COUNT(*) FROM customers WHERE registration_date=?',[$today]),'follow'=>DB::value("SELECT COUNT(*) FROM followups WHERE status='pending' AND due_date<=CURDATE()")]; $top=DB::select("SELECT s.name, SUM(ms.final_amount) revenue FROM massage_sessions ms JOIN services s ON s.id=ms.service_id WHERE ms.status='completed' GROUP BY s.id ORDER BY revenue DESC LIMIT 5"); ob_start(); ?><div class="row g-3"><?php foreach([['نوبت‌های امروز',$stats['appt'],'bi-calendar2-check'],['جلسات امروز',$stats['sessions'],'bi-clipboard-heart'],['درآمد امروز',money($stats['revenue']),'bi-cash'],['درآمد ماه',money($stats['month']),'bi-graph-up'],['مشتریان جدید',$stats['new'],'bi-person-plus'],['پیگیری معوق/امروز',$stats['follow'],'bi-telephone']] as $s): ?><div class="col-md-4 col-xl-2"><div class="stat"><i class="bi <?=$s[2]?>"></i><span><?=$s[0]?></span><b><?=$s[1]?></b></div></div><?php endforeach;?></div><div class="row g-3 mt-1"><div class="col-lg-8"><div class="card p-4"><h4>روند درآمد ۳۰ روز اخیر</h4><canvas id="revenueChart" data-url="<?=url('api.revenue')?>"></canvas></div></div><div class="col-lg-4"><div class="card p-4"><h4>خدمات برتر</h4><?php foreach($top as $r): ?><div class="d-flex justify-content-between border-bottom py-2"><span><?=e($r['name'])?></span><b><?=money($r['revenue'])?></b></div><?php endforeach;?></div></div></div><?php echo View::render('داشبورد', ob_get_clean()); exit; }
if($route==='api.revenue'){ header('Content-Type: application/json'); $rows=DB::select("SELECT massage_date d, SUM(final_amount) v FROM massage_sessions WHERE massage_date>=DATE_SUB(CURDATE(), INTERVAL 30 DAY) AND status='completed' GROUP BY massage_date ORDER BY massage_date"); echo json_encode(['labels'=>array_map(fn($r)=>Jalali::toJalali($r['d']),$rows),'values'=>array_map(fn($r)=>(float)$r['v'],$rows)], JSON_UNESCAPED_UNICODE); exit; }
if($route==='followups'){ Auth::requireCan('followups.view'); if($_SERVER['REQUEST_METHOD']==='POST'){ Auth::requireCan('followups.manage'); $id=(int)$_POST['id']; DB::update('followups',['status'=>$_POST['status'],'result'=>$_POST['result']??'', 'contacted_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],'id=:id',['id'=>$id]); $f=DB::row('SELECT * FROM followups WHERE id=?',[$id]); if($f) DB::insert('customer_timeline',['customer_id'=>$f['customer_id'],'type'=>'followup','title'=>'ثبت نتیجه پیگیری','body'=>($_POST['result']??$_POST['status']),'entity'=>'followups','entity_id'=>$id,'created_at'=>date('Y-m-d H:i:s')]); toast('نتیجه پیگیری ثبت شد.'); redirect('followups'); } $groups=['امروز'=>"due_date=CURDATE() AND status IN ('pending','requested_later')",'۷ روز آینده'=>"due_date>CURDATE() AND due_date<=DATE_ADD(CURDATE(), INTERVAL 7 DAY) AND status IN ('pending','requested_later')",'معوق'=>"due_date<CURDATE() AND status IN ('pending','requested_later')"]; ob_start(); foreach($groups as $title=>$w){ $rows=DB::select("SELECT f.*, CONCAT(c.first_name,' ',c.last_name) customer_name, c.mobile FROM followups f JOIN customers c ON c.id=f.customer_id WHERE $w ORDER BY due_date"); ?><div class="card p-3 mb-3"><h3><?=e($title)?></h3><div class="table-responsive"><table class="table"><tr><th>تاریخ</th><th>مشتری</th><th>موبایل</th><th>شرح</th><th>ثبت نتیجه</th></tr><?php foreach($rows as $r): ?><tr><td><?=Jalali::toJalali($r['due_date'])?></td><td><a href="<?=url('customers.show',['id'=>$r['customer_id']])?>"><?=e($r['customer_name'])?></a></td><td><?=e($r['mobile'])?></td><td><?=e($r['description'])?></td><td><form method="post" class="d-flex gap-1"><?=View::csrf()?><input type="hidden" name="id" value="<?=$r['id']?>"><select name="status" class="form-select form-select-sm"><option value="contacted">تماس گرفته شد</option><option value="not_answered">پاسخ نداد</option><option value="interested">علاقه‌مند</option><option value="booked">رزرو شد</option><option value="requested_later">تماس بعداً</option><option value="refused">رد کرد</option></select><input name="result" class="form-control form-control-sm" placeholder="یادداشت"><button class="btn btn-sm btn-primary">ثبت</button></form></td></tr><?php endforeach; if(!$rows): ?><tr><td colspan="5" class="empty">موردی وجود ندارد.</td></tr><?php endif;?></table></div></div><?php } echo View::render('مرکز پیگیری', ob_get_clean()); exit; }
if($route==='retention'){ $rows=RetentionService::metrics(); ob_start(); ?><div class="card p-4"><h3>هوشمندی نگهداشت مشتری (RFM)</h3><table class="table"><tr><th>مشتری</th><th>آخرین مراجعه</th><th>تعداد</th><th>ارزش مالی</th><th>بخش</th><th>پیشنهاد</th></tr><?php foreach($rows as $r): ?><tr><td><?=e($r['first_name'].' '.$r['last_name'])?></td><td><?=Jalali::toJalali($r['last_visit'])?></td><td><?=Jalali::fa($r['visits'])?></td><td><?=money($r['monetary'])?></td><td><?=status_badge($r['segment'])?></td><td><?=e(($r['segment']==='at_risk'||$r['segment']==='lost')?'تماس فوری و پیشنهاد تخفیف بازگشت':'حفظ ارتباط و پیشنهاد رزرو بعدی')?></td></tr><?php endforeach;?></table></div><?php echo View::render('نگهداشت مشتری', ob_get_clean()); exit; }
if($route==='finance' || $route==='reports'){ Auth::requireCan(($route==='finance'?'finance':'reports').'.view'); $from=Jalali::toGregorian($_GET['from']??date('Y-m-01')); $to=Jalali::toGregorian($_GET['to']??date('Y-m-d')); $rev=DB::row("SELECT COUNT(*) sessions, COALESCE(SUM(final_amount),0) revenue, COALESCE(SUM(discount),0) discounts FROM massage_sessions WHERE status='completed' AND massage_date BETWEEN ? AND ?",[$from,$to]); $exp=DB::value('SELECT COALESCE(SUM(amount),0) FROM expenses WHERE expense_date BETWEEN ? AND ? AND deleted_at IS NULL',[$from,$to]); ob_start(); ?><form class="card p-3 mb-3 d-flex flex-row gap-2"><input type="hidden" name="r" value="<?=e($route)?>"><input name="from" class="form-control" value="<?=Jalali::toJalali($from)?>"><input name="to" class="form-control" value="<?=Jalali::toJalali($to)?>"><button class="btn btn-primary">گزارش</button><a class="btn btn-soft" href="<?=url('export.csv',['from'=>$from,'to'=>$to])?>">خروجی CSV</a></form><div class="row g-3"><div class="col-md-3"><div class="stat"><span>درآمد</span><b><?=money($rev['revenue'])?></b></div></div><div class="col-md-3"><div class="stat"><span>هزینه</span><b><?=money($exp)?></b></div></div><div class="col-md-3"><div class="stat"><span>سود خالص</span><b><?=money($rev['revenue']-$exp)?></b></div></div><div class="col-md-3"><div class="stat"><span>تعداد جلسات</span><b><?=Jalali::fa($rev['sessions'])?></b></div></div></div><div class="card p-4 mt-3"><h4>درآمد بر اساس درمانگر/خدمت/منبع معرفی</h4><p>این بخش آماده چاپ و خروجی‌گیری است و داده‌ها از رکوردهای واقعی محاسبه می‌شود.</p></div><?php echo View::render($route==='finance'?'مالی':'گزارش‌ها', ob_get_clean()); exit; }
if($route==='export.csv'){ Auth::requireCan('reports.view'); header('Content-Type:text/csv; charset=utf-8'); header('Content-Disposition: attachment; filename=report.csv'); echo "date,customer,service,therapist,amount\n"; foreach(DB::select("SELECT ms.massage_date, CONCAT(c.first_name,' ',c.last_name) c, s.name s, t.name t, ms.final_amount FROM massage_sessions ms LEFT JOIN customers c ON c.id=ms.customer_id LEFT JOIN services s ON s.id=ms.service_id LEFT JOIN therapists t ON t.id=ms.therapist_id WHERE ms.massage_date BETWEEN ? AND ?",[$_GET['from'],$_GET['to']]) as $r) echo implode(',',array_map(fn($v)=>'"'.str_replace('"','""',(string)$v).'"',$r))."\n"; exit; }
if($route==='salaries'){ Auth::requireCan('salaries.view'); $therapists=DB::select("SELECT id,name FROM therapists WHERE status='active'"); $tid=(int)($_GET['therapist_id']??($therapists[0]['id']??0)); $from=Jalali::toGregorian($_GET['from']??date('Y-m-01')); $to=Jalali::toGregorian($_GET['to']??date('Y-m-d')); $calc=$tid?SalaryService::calculate($tid,$from,$to):[]; ob_start(); ?><form class="card p-3 mb-3 d-flex flex-row gap-2"><input type="hidden" name="r" value="salaries"><select name="therapist_id" class="form-select"><?php foreach($therapists as $t): ?><option value="<?=$t['id']?>" <?=$tid===$t['id']?'selected':''?>><?=e($t['name'])?></option><?php endforeach;?></select><input name="from" class="form-control" value="<?=Jalali::toJalali($from)?>"><input name="to" class="form-control" value="<?=Jalali::toJalali($to)?>"><button class="btn btn-primary">محاسبه</button></form><?php if($calc): ?><div class="card p-4"><h3>فیش محاسبات</h3><div class="row g-3"><div class="col"><div class="stat"><span>جلسات</span><b><?=Jalali::fa($calc['session_count'])?></b></div></div><div class="col"><div class="stat"><span>فروش</span><b><?=money($calc['gross'])?></b></div></div><div class="col"><div class="stat"><span>حقوق پایه</span><b><?=money($calc['base_salary'])?></b></div></div><div class="col"><div class="stat"><span>پورسانت</span><b><?=money($calc['commission'])?></b></div></div><div class="col"><div class="stat"><span>قابل پرداخت</span><b><?=money($calc['payable'])?></b></div></div></div></div><?php endif; echo View::render('حقوق و پورسانت', ob_get_clean()); exit; }
if($route==='users'){ Auth::requireCan('users.manage'); if($_SERVER['REQUEST_METHOD']==='POST'){ $data=['name'=>$_POST['name'],'email'=>$_POST['email'],'role_id'=>(int)$_POST['role_id'],'status'=>$_POST['status'],'permissions'=>json_encode($_POST['permissions']??[],JSON_UNESCAPED_UNICODE),'updated_at'=>date('Y-m-d H:i:s')]; if(!empty($_POST['password'])) $data['password_hash']=password_hash($_POST['password'],PASSWORD_DEFAULT); if(!empty($_POST['id'])) DB::update('users',$data,'id=:id',['id'=>(int)$_POST['id']]); else {$data['created_at']=date('Y-m-d H:i:s'); DB::insert('users',$data);} toast('کاربر ذخیره شد.'); redirect('users'); } $roles=DB::select('SELECT * FROM roles'); $users=DB::select('SELECT u.*, r.name role FROM users u JOIN roles r ON r.id=u.role_id ORDER BY u.id DESC'); ob_start(); ?><div class="row g-3"><div class="col-lg-5"><form method="post" class="card p-3"><?=View::csrf()?><h4>کاربر جدید</h4><input name="name" class="form-control mb-2" placeholder="نام"><input name="email" class="form-control mb-2" placeholder="ایمیل"><input name="password" class="form-control mb-2" placeholder="رمز عبور"><select name="role_id" class="form-select mb-2"><?php foreach($roles as $r): ?><option value="<?=$r['id']?>"><?=e($r['name'])?></option><?php endforeach;?></select><select name="status" class="form-select mb-2"><option value="active">فعال</option><option value="disabled">غیرفعال</option></select><textarea name="permissions[]" class="form-control mb-2" placeholder="مجوزهای اضافه"></textarea><button class="btn btn-primary">ذخیره</button></form></div><div class="col-lg-7"><div class="card p-3"><table class="table"><tr><th>نام</th><th>ایمیل</th><th>نقش</th><th>وضعیت</th></tr><?php foreach($users as $u): ?><tr><td><?=e($u['name'])?></td><td><?=e($u['email'])?></td><td><?=e($u['role'])?></td><td><?=status_badge($u['status'])?></td></tr><?php endforeach;?></table></div></div></div><?php echo View::render('کاربران و نقش‌ها', ob_get_clean()); exit; }
if($route==='settings'){ Auth::requireCan('settings.manage'); if($_SERVER['REQUEST_METHOD']==='POST'){ foreach($_POST['settings']??[] as $k=>$v){ DB::exec('INSERT INTO settings (`key`,`value`) VALUES (?,?) ON DUPLICATE KEY UPDATE value=VALUES(value)',[$k,$v]); } toast('تنظیمات ذخیره شد.'); redirect('settings'); } $keys=['brand_name'=>'نام برند','primary_color'=>'رنگ اصلی','secondary_color'=>'رنگ دوم','website_title'=>'عنوان وب‌سایت','contact_phone'=>'تلفن','address'=>'آدرس','default_followup_days'=>'بازه پیگیری پیش‌فرض','currency'=>'واحد پول','default_theme'=>'تم پیش‌فرض']; ob_start(); ?><form method="post" class="card p-4"><?=View::csrf()?><div class="row g-3"><?php foreach($keys as $k=>$l): ?><div class="col-md-6"><label class="form-label"><?=$l?></label><input name="settings[<?=$k?>]" value="<?=e(View::setting($k,''))?>" class="form-control"></div><?php endforeach;?></div><button class="btn btn-primary mt-3">ذخیره</button></form><?php echo View::render('تنظیمات', ob_get_clean()); exit; }
if($route==='backup'){ Auth::requireCan('backup.manage'); $error=null; if($_SERVER['REQUEST_METHOD']==='POST'){ try{BackupService::create(); toast('پشتیبان تهیه شد.'); redirect('backup');}catch(Throwable $e){$error=$e->getMessage();}} ob_start(); if($error) echo '<div class="alert alert-danger">'.e($error).'</div>'; ?><div class="card p-4"><form method="post"><?=View::csrf()?><button class="btn btn-primary">ایجاد بکاپ دستی</button></form><h4 class="mt-4">فایل‌های بکاپ</h4><ul><?php foreach(BackupService::list() as $f): ?><li><?=e($f)?></li><?php endforeach;?></ul><p class="text-muted">برای بکاپ زمان‌بندی‌شده از cron طبق مستندات استفاده کنید.</p></div><?php echo View::render('پشتیبان‌گیری', ob_get_clean()); exit; }
if($route==='audit'){ Auth::requireCan('audit.view'); $rows=DB::select('SELECT a.*, u.name user FROM audit_logs a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.id DESC LIMIT 200'); ob_start(); ?><div class="card p-3"><table class="table"><tr><th>زمان</th><th>کاربر</th><th>عمل</th><th>رکورد</th><th>IP</th></tr><?php foreach($rows as $r): ?><tr><td><?=Jalali::toJalali($r['created_at'])?></td><td><?=e($r['user'])?></td><td><?=e($r['action'])?></td><td><?=e($r['entity'].' #'.$r['entity_id'])?></td><td><?=e($r['ip_address'])?></td></tr><?php endforeach;?></table></div><?php echo View::render('ممیزی', ob_get_clean()); exit; }
http_response_code(404); echo View::render('یافت نشد','<div class="alert alert-warning">صفحه یافت نشد.</div>');
